version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT_STATS=9090
      - SPRING_DATASOURCE_URL_STATS=jdbc:postgresql://stats-db:5432/explore-with-me
      - SPRING_DATASOURCE_USERNAME_STATS=postgres
      - SPRING_DATASOURCE_PASSWORD_STATS=postgres
      - SPRING_DATASOURCE_DRIVER_STATS=org.postgresql.Driver


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: explore-with-me
