version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT_STATS=9090
      - SPRING_DATASOURCE_URL_STATS=jdbc:postgresql://stats-db:5432/EWM-stats
      - SPRING_DATASOURCE_USERNAME_STATS=postgres
      - SPRING_DATASOURCE_PASSWORD_STATS=postgres
      - SPRING_DATASOURCE_DRIVER_STATS=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EWM-stats


  ewm-service:
    build: main-service
    image: ewm-main-image
    container_name: ewm-main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_PORT_STATS=8080
      - SPRING_DATASOURCE_URL_MAIN=jdbc:postgresql://ewm-db:5432/EWM-main
      - SPRING_DATASOURCE_USERNAME_MAIN=postgres
      - SPRING_DATASOURCE_PASSWORD_MAIN=postgres
      - SPRING_DATASOURCE_DRIVER_MAIN=org.postgresql.Driver


  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EWM-main