CREATE TABLE IF NOT EXISTS hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255)                NOT NULL,
    uri       VARCHAR(255)                NOT NULL,
    ip        VARCHAR(15)                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_hit_uri ON hit USING hash (uri);
CREATE INDEX IF NOT EXISTS idx_hit_timestamp ON hit (timestamp);